### GET request to example server
GET http://localhost:8080/v1/api/accounts/1

###
#create users
POST http://localhost:8080/v1/api/accounts
Content-Type: application/json

{
  "accountHolderName": "Jamir ",
  "balance": 200000.00
}

###

PUT http://localhost:8080/v1/api/accounts/3/deposit
Content-Type: application/json

{
  "amount": 300000.00
}
###

PUT http://localhost:8080/v1/api/accounts/6/withdraw
Content-Type: application/json

{
  "amount": 10000000.00
}


###

GET http://localhost:8080/v1/api/accounts

###

GET http://localhost:8080/v1/api/accounts




